# Generated by Django 5.2.6 on 2025-10-01 00:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0002_alter_visita_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='fecha_de_visita',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
