# Generated by Django 5.2.6 on 2025-10-01 00:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0003_alter_visita_fecha_de_visita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='fecha_de_visita',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='visita',
            name='rut',
            field=models.CharField(max_length=12),
        ),
    ]
