# Generated by Django 4.2.25 on 2025-10-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitas', '0004_alter_visita_fecha_de_visita_alter_visita_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visita',
            name='rut',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
